[package]
name = "rust-demultiplex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.3"
anyhow = "1.0"
flate2 = "1.0.27"
clap = { version = "3.1.18", features = ["derive"] }
